version = 1
SPDX-PackageName = "SAP-docs/btp-cloud-integration-automation-service"
SPDX-PackageSupplier = "Rashi Gupta (rashi.gupta01@sap.com)"
SPDX-PackageDownloadLocation = "https://github.com/sap-docs/btp-cloud-integration-automation-service"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and SAP-docs/btp-cloud-integration-automation-service contributors"
SPDX-License-Identifier = "CC-BY-4.0"
